<?php

namespace App\Filament\App\Resources\ConfigResource\Pages;

use App\Filament\App\Resources\ConfigResource;
use App\Models\Config;
use Filament\Actions;
use Filament\Resources\Pages\ListRecords;

class ListConfigs extends ListRecords
{
    protected static string $resource = ConfigResource::class;


    public function mount(): void
    {
        $id = auth()->id();

        if ($config = Config::query()->where('user_id', $id)->first()) {
            $redirect = 'app/configuracoes/'.$config->id.'/edit';
          redirect($redirect);
        } else {
            redirect('app/configuracoes/create');
        }

        parent::mount(); // TODO: Change the autogenerated stub
    }

    protected function getHeaderActions(): array
    {
        return [
            Actions\CreateAction::make(),
        ];
    }
}
